name: PR Lint
on: pull_request

jobs:
  pr-lint:
    name: "PR Lint"
    runs-on: ubuntu-latest
    steps:
      # Checkout files from repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Run markdown linting
      - name: markdownlint-cli
        uses: actionshub/markdownlint@main

      # Run TF validation
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.3.6

      - name: Terraform validation
        id: init
        run: terraform init && terraform validate

      - name: Terraform format
        id: fmt
        run: terraform fmt -check -recursive
